"""OpenCode integration for logpose — spawn plan, build, refine, and review processes."""

import os
import subprocess
import shutil


def _find_opencode():
    """Find the opencode binary. Returns path or None."""
    p = os.path.expanduser("~/.opencode/bin/opencode")
    return shutil.which("opencode") or (p if os.path.isfile(p) else None)


def _check_opencode():
    """Verify opencode is installed and available."""
    binary = _find_opencode()
    if not binary:
        raise RuntimeError(
            "OpenCode not found. Install it with:\n"
            "  npm i -g opencode-ai@latest\n"
            "or: brew install anomalyco/tap/opencode"
        )
    return binary


def _slugify(text):
    """Simple slug for filenames."""
    import re
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[-\s]+", "-", text)
    return text[:60]


def run_refine(idea_id, idea_title, idea_description, project_path, model=None):
    """Run opencode to refine an idea into a well-structured specification.

    Captures opencode's stdout and returns the refined description text.
    """
    binary = _check_opencode()

    prompt = (
        f"You are a product spec writer. Refine the following idea into a clear, actionable task specification.\n\n"
        f"RULES:\n"
        f"- Focus on WHAT needs to be done, not HOW to implement it\n"
        f"- Do NOT include implementation details, file paths, code snippets, or architectural decisions\n"
        f"- Include: problem statement, desired outcome, scope, constraints, acceptance criteria\n"
        f"- Keep it concise but complete — someone else will plan the implementation from this\n\n"
        f"IDEA:\n"
        f"Title: {idea_title}\n"
        f"Description: {idea_description or '(no description provided)'}\n\n"
        f"Read AGENTS.md in the project root for project context before writing the refinement.\n\n"
        f"Output ONLY the refined description — no headers, no meta-commentary, just the spec."
    )

    print(f"[logpose] Running refine for idea #{idea_id}...")
    print(f"[logpose] Project: {project_path}")

    cmd = [binary, "run", "--agent", "plan", prompt]
    if model:
        cmd.extend(["-m", model])

    result = subprocess.run(
        cmd,
        cwd=project_path,
        capture_output=True,
        text=True,
        timeout=300,
    )

    output = (result.stdout or "").strip()

    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        print(f"[logpose] WARNING: opencode exited with code {result.returncode}")
        if stderr:
            print(f"[logpose] stderr: {stderr[:500]}")

    if not output:
        print("[logpose] WARNING: opencode produced no output. Refinement failed.")
        return None

    print(f"[logpose] Refinement complete ({len(output)} chars)")
    return output


def run_plan(task_id, task_title, task_description, project_path, plan_output_dir=None, model=None):
    """Run opencode plan agent for a task.

    Captures opencode's stdout, saves it as the plan markdown file.
    Returns the path to the saved plan markdown file.
    """
    binary = _check_opencode()

    if plan_output_dir is None:
        plan_output_dir = os.path.join(project_path, "plans")
    os.makedirs(plan_output_dir, exist_ok=True)

    plan_filename = f"task-{task_id}-{_slugify(task_title)}.md"
    plan_path = os.path.join(plan_output_dir, plan_filename)

    prompt = (
        f"Create an implementation plan for this task. "
        f"Read AGENTS.md for project context. "
        f"Write bite-sized implementation steps with exact file paths, code snippets, and test commands.\n\n"
        f"Task: {task_title}\n\n"
        f"{task_description}"
    )

    print(f"[logpose] Running plan for task #{task_id}...")
    print(f"[logpose] Project: {project_path}")

    cmd = [binary, "run", "--agent", "plan", prompt]
    if model:
        cmd.extend(["-m", model])

    result = subprocess.run(
        cmd,
        cwd=project_path,
        capture_output=True,
        text=True,
        timeout=600,
    )

    output = (result.stdout or "").strip()

    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        print(f"[logpose] WARNING: opencode exited with code {result.returncode}")
        if stderr:
            print(f"[logpose] stderr: {stderr[:500]}")

    if output:
        with open(plan_path, "w") as f:
            f.write(f"# Plan for: {task_title}\n\n")
            f.write(f"> Task #{task_id} | Generated by opencode plan agent\n\n")
            f.write(output)
        print(f"[logpose] Plan saved: {plan_path} ({len(output)} chars)")
    else:
        print(f"[logpose] WARNING: opencode produced no output. Plan file not written.")
        return None

    return plan_path


def run_build(task_id, task_title, task_description, project_path, plan_md_path=None, log_path=None, model=None):
    """Run opencode build for a task.

    Spawns `opencode run '...' -f plan.md` in the project directory.
    Uses --dangerously-skip-permissions so file operations auto-approve in
    non-interactive (no-PTY) subprocess contexts. This only affects the
    subprocess spawned by `lg task build` — interactive opencode TUI sessions
    are unaffected.
    Streams output to the user and captures it to a log file.
    Returns (exit_code, log_path).
    """
    binary = _check_opencode()

    # Generate log path in centralized location if not provided
    if log_path is None:
        log_dir = os.path.join(os.path.expanduser("~/.logpose"), "logs")
        os.makedirs(log_dir, exist_ok=True)
        slug = _slugify(task_title)
        log_path = os.path.join(log_dir, f"task-{task_id}-{slug}.log")

    # Ensure log directory exists
    log_dir = os.path.dirname(log_path)
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)

    prompt = (
        f"Implement this task following the plan. "
        f"Follow TDD: write failing tests first, then implement, then verify tests pass. "
        f"Commit your changes with descriptive messages. "
        f"Read AGENTS.md for project conventions.\n\n"
        f"Task: {task_title}\n\n"
        f"{task_description}"
    )

    cmd = [binary, "run", "--dangerously-skip-permissions", prompt]
    if plan_md_path and os.path.isfile(plan_md_path):
        cmd.extend(["-f", plan_md_path])
        print(f"[logpose] Attaching plan: {plan_md_path}")
    if model:
        cmd.extend(["-m", model])

    print(f"[logpose] Running build for task #{task_id}...")
    print(f"[logpose] Project: {project_path}")
    print(f"[logpose] Log: {log_path}")

    proc = subprocess.Popen(
        cmd,
        cwd=project_path,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    # Tee output: print each line and write to log file
    with open(log_path, "w") as log_file:
        for line in proc.stdout:
            print(line, end="")
            log_file.write(line)
            log_file.flush()
    proc.wait()

    if proc.returncode == 0:
        print(f"[logpose] Build complete for task #{task_id}.")
    else:
        print(f"[logpose] Build FAILED for task #{task_id} (exit code {proc.returncode}).")

    return proc.returncode, log_path


def run_review(task_id, task_title, task_description, project_path, plan_md_path=None, model=None):
    """Run opencode review agent for a task.

    Reviews the implementation for spec compliance and code quality.
    Returns the path to the saved review log file.
    """
    binary = _check_opencode()

    log_dir = os.path.join(os.path.expanduser("~/.logpose"), "logs")
    os.makedirs(log_dir, exist_ok=True)
    slug = _slugify(task_title)
    log_path = os.path.join(log_dir, f"review-{task_id}-{slug}.log")

    review_prompt = (
        f"Review the implementation of this task for spec compliance and code quality.\n\n"
        f"TASK SPEC:\n"
        f"Title: {task_title}\n"
        f"Description: {task_description}\n\n"
        f"CHECK LIST:\n"
        f"1. [ ] All requirements from the spec are implemented?\n"
        f"2. [ ] File paths and function signatures match the spec?\n"
        f"3. [ ] Behavior matches the expected outcome?\n"
        f"4. [ ] Tests cover the spec requirements?\n"
        f"5. [ ] No scope creep (only what was asked for)?\n"
        f"6. [ ] Proper error handling?\n"
        f"7. [ ] Clear variable/function names?\n"
        f"8. [ ] No obvious bugs or missed edge cases?\n"
        f"9. [ ] No security issues?\n"
        f"10. [ ] Follows project conventions in AGENTS.md?\n\n"
        f"Read AGENTS.md for project conventions.\n\n"
        f"OUTPUT FORMAT:\n"
        f"- Spec Compliance: PASS or list of gaps\n"
        f"- Code Quality: PASS or list of issues\n"
        f"- Verdict: APPROVED or REQUEST_CHANGES\n"
    )

    cmd = [binary, "run", "--agent", "plan", review_prompt]
    if plan_md_path and os.path.isfile(plan_md_path):
        cmd.extend(["-f", plan_md_path])
        print(f"[logpose] Attaching plan: {plan_md_path}")
    if model:
        cmd.extend(["-m", model])

    print(f"[logpose] Running review for task #{task_id}...")
    print(f"[logpose] Project: {project_path}")
    print(f"[logpose] Log: {log_path}")

    result = subprocess.run(
        cmd,
        cwd=project_path,
        capture_output=True,
        text=True,
        timeout=600,
    )

    output = (result.stdout or "").strip()

    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        print(f"[logpose] WARNING: opencode exited with code {result.returncode}")
        if stderr:
            print(f"[logpose] stderr: {stderr[:500]}")

    if output:
        with open(log_path, "w") as f:
            f.write(f"# Review for: {task_title}\n\n")
            f.write(f"> Task #{task_id} | Generated by opencode review agent\n\n")
            f.write(output)
        print(f"[logpose] Review saved: {log_path} ({len(output)} chars)")
    else:
        print("[logpose] WARNING: opencode produced no review output.")
        return None

    return log_path