"""OpenCode integration for logpose — spawn plan and build processes."""

import os
import subprocess
import shutil


def _find_opencode():
    """Find the opencode binary. Returns path or None."""
    candidates = [
        shutil.which("opencode"),
        os.path.expanduser("~/.opencode/bin/opencode"),
    ]
    for c in candidates:
        if c and os.path.isfile(c):
            return c
    return shutil.which("opencode")


def _check_opencode():
    """Verify opencode is installed and available."""
    binary = _find_opencode()
    if not binary:
        raise RuntimeError(
            "OpenCode not found. Install it with:\n"
            "  npm i -g opencode-ai@latest\n"
            "or: brew install anomalyco/tap/opencode"
        )
    return binary


def run_plan(task_id, task_title, task_description, project_path, plan_output_dir=None, model=None):
    """Run opencode plan agent for a task.

    Captures opencode's stdout, saves it as the plan markdown file.
    Returns the path to the saved plan markdown file.
    """
    binary = _check_opencode()

    if plan_output_dir is None:
        plan_output_dir = os.path.join(project_path, "plans")
    os.makedirs(plan_output_dir, exist_ok=True)

    plan_filename = f"task-{task_id}-{_slugify(task_title)}.md"
    plan_path = os.path.join(plan_output_dir, plan_filename)

    prompt = (
        f"Create an implementation plan for this task. "
        f"Read AGENTS.md for project context. "
        f"Write bite-sized implementation steps with exact file paths, code snippets, and test commands.\n\n"
        f"Task: {task_title}\n\n"
        f"{task_description}"
    )

    print(f"[tix] Running opencode plan for task #{task_id}...")
    print(f"[tix] Project: {project_path}")

    cmd = [binary, "run", "--agent", "plan", prompt]
    if model:
        cmd.extend(["-m", model])

    result = subprocess.run(
        cmd,
        cwd=project_path,
        capture_output=True,
        text=True,
        timeout=600,
    )

    output = (result.stdout or "").strip()

    if result.returncode != 0:
        stderr = (result.stderr or "").strip()
        print(f"[tix] WARNING: opencode exited with code {result.returncode}")
        if stderr:
            print(f"[tix] stderr: {stderr[:500]}")

    if output:
        with open(plan_path, "w") as f:
            f.write(f"# Plan for: {task_title}\n\n")
            f.write(f"> Task #{task_id} | Generated by opencode plan agent\n\n")
            f.write(output)
        print(f"[tix] Plan saved: {plan_path} ({len(output)} chars)")
    else:
        print(f"[tix] WARNING: opencode produced no output. Plan file not written.")
        return None

    return plan_path


def run_build(task_id, task_title, task_description, project_path, plan_md_path=None, log_path=None, model=None):
    """Run opencode build for a task.

    Spawns `opencode run '...' -f plan.md` in the project directory.
    Streams output to the user and captures it to a log file.
    Returns (exit_code, log_path).
    """
    binary = _check_opencode()

    # Generate log path in centralized location if not provided
    if log_path is None:
        log_dir = os.path.join(os.path.expanduser("~/.logpose"), "logs")
        os.makedirs(log_dir, exist_ok=True)
        slug = _slugify(task_title)
        log_path = os.path.join(log_dir, f"task-{task_id}-{slug}.log")

    # Ensure log directory exists
    log_dir = os.path.dirname(log_path)
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)

    prompt = (
        f"Implement this task following the plan. "
        f"Follow TDD: write failing tests first, then implement, then verify tests pass. "
        f"Commit your changes with descriptive messages. "
        f"Read AGENTS.md for project conventions.\n\n"
        f"Task: {task_title}\n\n"
        f"{task_description}"
    )

    cmd = [binary, "run", prompt]
    if plan_md_path and os.path.isfile(plan_md_path):
        cmd.extend(["-f", plan_md_path])
        print(f"[tix] Attaching plan: {plan_md_path}")
    if model:
        cmd.extend(["-m", model])

    print(f"[tix] Running opencode build for task #{task_id}...")
    print(f"[tix] Project: {project_path}")
    print(f"[tix] Log: {log_path}")

    proc = subprocess.Popen(
        cmd,
        cwd=project_path,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    # Tee output: print each line and write to log file
    with open(log_path, "w") as log_file:
        for line in proc.stdout:
            print(line, end="")
            log_file.write(line)
            log_file.flush()
    proc.wait()

    if proc.returncode == 0:
        print(f"[tix] Build complete for task #{task_id}.")
    else:
        print(f"[tix] Build FAILED for task #{task_id} (exit code {proc.returncode}).")

    return proc.returncode, log_path


def _slugify(text):
    """Simple slug for filenames."""
    import re
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[-\s]+", "-", text)
    return text[:60]
